repos:
  -   repo: https://github.com/mgedmin/check-manifest
      rev: "0.50"
      hooks:
        -   id: check-manifest
            additional_dependencies: [setuptools, scikit-build, wheel, setuptools-scm]