# InstallOpenMP.cmake
if (OpenMP_CXX_LIBRARIES)
    foreach (lib ${OpenMP_CXX_LIBRARIES})
        get_filename_component(lib_path ${lib} ABSOLUTE)
        if (EXISTS ${lib_path} AND NOT lib_path MATCHES "^/lib.*|/usr/lib.*")
            message(STATUS "Installing OpenMP runtime library: ${lib_path}")
            install(FILES ${lib_path} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
        else ()
            message(STATUS "Skipping OpenMP runtime: ${lib_path} is system-provided")
        endif ()
    endforeach ()
else ()
    message(WARNING "OpenMP_CXX_LIBRARIES is empty — OpenMP runtime will not be bundled.")
endif ()
