package:
  name: egttools
  version: 0.1.5.dev4

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
    - cmake >=3.18
    - ninja
    - eigen3

  run:
    - python
    - numpy>=1.7
    - scipy>=1.5
    - matplotlib>=3.3
    - networkx


test:
  imports:
    - egttools
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: Analytical and numerical methods for Evolutionary Game Theory.
  license_file: LICENSE