{% set version = "0.1.5.dev4" %}

package:
  name: egttools
  version: {{ version }}

source:
  git_url: https://github.com/Socrats/EGTTools
  git_tag: {{ version }}

build:
  number: 0
  features:
    - nomkl  [nomkl]

requirements:
  build:
    - python
    - cmake
    - numpy x.x
    - eigen 3.*

  run:
    - python
    - numpy x.x

test:
  imports:
    - egttools
    - egttools.numerical

  commands:


about:
  home: http://opencv.org/
  license: BSD 3-clause
  license_family: BSD
  summary: Computer vision and machine learning software library.
  description: |
    OpenCV (Open Source Computer Vision Library) includes several hundreds of computer vision algorithms.
    It has a modular structure,which means that the package includes several shared or static libraries.
  doc_url: http://docs.opencv.org/
  doc_source_url: https://github.com/opencv/opencv/tree/master/doc