name: Build MacosX

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  wheels:
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-10.15
            cibw-arch: macosx_x86_64
          - runs-on: macos-latest
            cibw-arch: macosx_arm64
          - runs-on: macos-10.15
            cibw-arch: macosx_universal2

    name: Wheels • ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD_FRONTEND: "build"
          CIBW_BUILD: "cp*-${{ matrix.cibw-arch }}"
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_BEFORE_ALL: pip install --upgrade pip
          CIBW_BEFORE_BUILD_MACOS: brew install eigen && brew install libomp && brew install gfortran && brew install openblas && export LIBOMP=$(brew --prefix libomp)
          CIBW_BUILD_VERBOSITY: 3
          CIBW_SKIP: "cp310-*"
          CIBW_ENVIRONMENT: CMAKE_BUILD_PARALLEL_LEVEL=2
          CIBW_ENVIRONMENT_MACOS: CMAKE_BUILD_PARALLEL_LEVEL=2 CMAKE_OSX_ARCHITECTURES=${{ matrix.cibw-arch == 'macosx_x86_64' && 'x86_64' || matrix.cibw-arch == 'macosx_arm64' && 'arm64' || matrix.cibw-arch == 'macosx_universal2' && '"arm64;x86_64"' || '' }} BUILD_ARCH=${{ matrix.cibw-arch }} MACOSX_DEPLOYMENT_TARGET=10.15 EGTTOOLS_EXTRA_CMAKE_ARGS='-DSKIP_OPENMP:BOOL=FALSE' CONDA_PREFIX=$CONDA
          CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"
          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST: cd .. && cp -r EGTTools/tests/ /Users/runner/tests/
          CIBW_TEST_COMMAND: pytest tests

      - name: Upload built wheels
        if: startsWith(github.ref, 'refs/heads/docs') != true
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/egttools-*.whl
          if-no-files-found: error

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true