name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - fix_github_ci
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            python: "3.10"
            openmp_enabled: "ON"
            platform: linux-x86_64

          - runs-on: macos-13
            python: "3.10"
            openmp_enabled: "OFF"  # No OpenMP for easier documentation build
            platform: macos-x86_64

    name: Python ${{ matrix.python }} • ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev libeigen3-dev libboost-all-dev
          echo "EGTTOOLS_EXTRA_CMAKE_ARGS=-DUSE_OPENMP=${{ matrix.openmp_enabled }}" >> $GITHUB_ENV

      - name: Install system dependencies macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install eigen boost
          echo "EGTTOOLS_EXTRA_CMAKE_ARGS=-DUSE_OPENMP=${{ matrix.openmp_enabled }}" >> $GITHUB_ENV

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m pip install -r tests/requirements.txt

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -DPython_EXECUTABLE="$(which python)" $EGTTOOLS_EXTRA_CMAKE_ARGS

      - name: Build and install
        run: |
          cmake --build build --parallel
          pip install .

      - name: Test
        run: |
          python build_tools/github/check_if_egttools_is_installed.py
          pytest tests -s --import-mode=importlib

      - name: Setup tmate session (on failure)
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-file: docs/environment.yml

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev libeigen3-dev libboost-all-dev pandoc
          echo "EGTTOOLS_EXTRA_CMAKE_ARGS=-DUSE_OPENMP=OFF" >> $GITHUB_ENV

      - name: Configure project
        run: |
          cmake -S . -B build -DPython_EXECUTABLE="$(which python)" $EGTTOOLS_EXTRA_CMAKE_ARGS

      - name: Build Python wheel and install
        run: |
          cmake --build build --parallel
          pip install .

      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Check documentation links
        run: |
          sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Setup tmate session (on failure)
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
