
name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            python: 3.6
            arch: x64
          - runs-on: ubuntu-latest
            python: 3.7
            arch: x64
          - runs-on: ubuntu-latest
            python: 3.8
            arch: x64
          - runs-on: ubuntu-latest
            python: 3.9
            arch: x64
          - runs-on: ubuntu-latest
            python: pypy-3.6
            arch: x64
          - runs-on: ubuntu-latest
            python: pypy-3.7
            arch: x64

          - runs-on: ubuntu-latest
            python: 3.9
            arch: x64
            gcc: 10
            name-extra: ' (GCC 10)'
          - runs-on: ubuntu-latest
            python: 3.9
            arch: x64
            clang: 9
            name-extra: ' (Clang 9)'

          - runs-on: ubuntu-latest
            python: 3.6
            arch: x64
            release: true
            name-extra: ' (Release)'
          - runs-on: ubuntu-latest
            python: 3.9
            arch: x64
            release: true
            name-extra: ' (Release)'

          - runs-on: macos-latest
            python: 3.6
            arch: x64
          - runs-on: macos-latest
            python: 3.9
            arch: x64
          - runs-on: macos-latest
            python: 3.9
            arch: x64
            release: true
            name-extra: ' (Release)'
          - runs-on: macos-latest
            python: pypy-3.6
            arch: x64

          - runs-on: windows-latest
            python: 3.6
            arch: x64
          - runs-on: windows-latest
            python: 3.9
            arch: x64
          - runs-on: windows-latest
            python: 3.6
            arch: x86
            name-extra: ' (32-bit)'
          - runs-on: windows-latest
            python: 3.9
            arch: x86
            name-extra: ' (32-bit)'
          - runs-on: windows-latest
            python: 3.6
            arch: x64
            release: true
            name-extra: ' (Release)'
          - runs-on: windows-latest
            python: pypy-3.6
            arch: x86

    name: Python ${{ matrix.python }}${{ matrix.name-extra }} • ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    if: startsWith(github.ref, 'refs/heads/docs') != true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8

      - name: Install OpenMP and Eigen3 on macOS
        if: runner.os == 'macOS'
        run: |
          brew install libomp
          echo "LIBOMP=$(brew --prefix libomp)" >> $GITHUB_ENV
          brew install eigen
          echo "EIGEN=$(brew --prefix eigen)" >> $GITHUB_ENV
      - name: install openMP and Eigen3 on ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libomp-dev
          sudo apt install libeigen3-dev
      - name: install Eigen3 windows
        if: runner.os == 'Windows'
        run: |
          curl.exe --output eigen-3.3.9.tar.gz --url https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
          tar -zxvf eigen-3.3.9.tar.gz "C:\"
          ren "C:\eigen-3.3.9" "C:\eigen3"

      - name: Install OpenBLAS on macOS for NumPy
        if: runner.os == 'macOS' && startsWith(matrix.python, 'pypy')
        run: |
          brew install openblas
          echo "OPENBLAS=$(brew --prefix openblas)" >> $GITHUB_ENV
      - name: Install requirements
        run: |
          pip install --user --upgrade pip setuptools wheel build
          pip install --user --upgrade -r tests/requirements.txt
      - name: Select GCC
        if: matrix.gcc
        shell: bash
        run: |
          echo "CC=gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.gcc }}" >> $GITHUB_ENV
      - name: Select Clang
        if: matrix.clang
        shell: bash
        run: |
          echo "CC=clang-${{ matrix.clang }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.clang }}" >> $GITHUB_ENV
      - name: Setup pytest annotations
        run: |
          python -m pip install pytest-github-actions-annotate-failures
      - name: Setup GCC annotations
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Setup MSVC annotations
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Configure
        shell: bash
        run: |
          CMAKE_ARCH="${{ (runner.os == 'Windows' && matrix.arch == 'x86') && '-A Win32' || '' }}"
          CMAKE_BUILD_TYPE="${{ matrix.release && 'Release' || 'Debug' }}"
          cmake -S . -B build $CMAKE_ARCH -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DPython_EXECUTABLE="$(which python)"

      - name: Compile
        run: |
          cmake --build build -j 2 --target egttools
  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8

      - name: Install requirements
        run: |
          pip install --user -r docs/requirements.txt
          sudo apt install pandoc

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -DPython_EXECUTABLE="$(which python)"

      - name: Build
        run: |
          cmake --build build -j 2 --target egttools
      - name: Build documentation
        run: |
          cmake --build build --target docs
      - name: Check links
        run: |
          cmake --build build --target docs_linkcheck