name: Deploy Documentation

on:
  push:
    branches:
      - master  # Only trigger on pushes to master

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev libeigen3-dev libboost-all-dev pandoc
          echo "EGTTOOLS_EXTRA_CMAKE_ARGS=-DUSE_OPENMP=OFF" >> $GITHUB_ENV

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install -r docs/requirements.txt

      - name: Configure project
        run: |
          cmake -S . -B build -DPython_EXECUTABLE="$(which python)" $EGTTOOLS_EXTRA_CMAKE_ARGS

      - name: Build Python package
        run: |
          cmake --build build --parallel
          pip install .

      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Check documentation links
        run: |
          sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          force_orphan: true
