name: Build Docs

on:
  workflow_run:
    workflows: [ "Build Wheels" ]
    types:
      - completed
  workflow_dispatch:   # Allow manual triggering too

jobs:
  build-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built wheels artifact
        uses: actions/download-artifact@v4
        with:
          name: rtd-wheel
          path: ./wheelhouse

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install EGTtools from built wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install wheelhouse/*.whl

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install documentation dependencies
        run: |
          pip install .[docs] pandoc

      - name: Build documentation
        run: |
          sphinx-build -b html -n --keep-going docs build/html

      - name: Check documentation links
        run: |
          sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: built-docs
          path: docs/_build/html

  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-docs
    if: success()

    steps:
      - name: Download built documentation
        uses: actions/download-artifact@v4
        with:
          name: built-docs
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          force_orphan: true