name: Build Documentation

on:
  push:
    branches:
      - master
      - fix_github_ci
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run with tmate debugging enabled'
        required: false
        default: false

jobs:
  build-docs:
    name: Documentation Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built wheel
        uses: actions/download-artifact@v4
        with:
          name: rtd-wheel
          path: wheelhouse

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m pip install --no-deps -r docs/requirements.txt
          python -m pip install wheelhouse/*.whl

      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Check documentation links
        run: |
          sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: Setup tmate session (optional debug)
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
