name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build with Pip
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]
        python-version: [ "3.8", "3.9" ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8

      - name: Install system dependencies macOS
        if: runner.os == 'macOS'
        run: |
          brew install libomp
          echo "LIBOMP=$(brew --prefix libomp)" >> $GITHUB_ENV
          brew install eigen
          echo "EIGEN=$(brew --prefix eigen)" >> $GITHUB_ENV
          brew install gfortran
          echo "GFORTRAN=$(brew --prefix gfortran)" >> $GITHUB_ENV
          brew install openblas
          echo "OPENBLAS=$(brew --prefix openblas)" >> $GITHUB_ENV
      - name: Install system dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libomp-dev
          sudo apt-get install libeigen3-dev
          echo "Eigen3_DIR='/usr/include/eigen3'" >> $GITHUB_ENV

      - name: Add requirements
        run: |
          python -m pip install --upgrade wheel setuptools
          python -m pip install --upgrade -r tests/requirements.txt

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Test
        run: pytest tests