name: Wheels Windows

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
  pull_request:
  push:
    branches:
      - develop

jobs:
  build_wheels:
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # Run 32 and 64 bit version in parallel for Linux and Windows
          - runs-on: windows-latest
            cibw-arch: win_amd64
#          - runs-on: windows-latest
#            cibw-arch: win32
#            python-arch: x86

    name: Wheels • ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: ${{ matrix.python-arch }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_BUILD_FRONTEND: "build"
          CIBW_BUILD: "cp*-${{ matrix.cibw-arch }}"
          CIBW_SKIP: "cp37*"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_BEFORE_ALL: pip install --upgrade pip
          CIBW_BEFORE_ALL_WINDOWS: bash build_tools/github/download_eigen3_windows.sh
          CIBW_ENVIRONMENT: CMAKE_BUILD_PARALLEL_LEVEL=2
          CIBW_ENVIRONMENT_WINDOWS: |
            CMAKE_BUILD_PARALLEL_LEVEL=2 
            CMAKE_ARCH="${{ matrix.platform_id == 'win32' && '-A Win32' || '' }}"
            BOOST_ROOT=c:/local/boost_1_82_0
            BOOST_LIBRARYDIR=c:/local/boost_1_82_0/lib64-msvc-14.3

          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST_WINDOWS: cd .. && cp -r {package}/tests/ {project}\tests\
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_BUILD_VERBOSITY: 1

      - name: Upload wheels
        if: startsWith(github.ref, 'refs/heads/docs') != true
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/egttools-*.whl
          if-no-files-found: error

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true